title: Duyen (Doo-win) Nguyen # your name (or website title) here
logo: "/images/IMG_7492.jpeg?raw=true" # your photo (or logo) here images/IMG_7492.jpeg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Duyen, A Master's student in Applied Data Science @ USC looking for Spring/Summer 2022 internship opportunities to use and expand my skillset. I'm interested in the field of data analytics/data science and open to learn new skills.
  <br><br>
  Hope to connect with you soon!
  <br><br>
  <a href="https://www.linkedin.com/in/duyen21/">View My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-650SVG95FP # your Google Analytics tracking ID here
