title: Duyen (Doo-win) Nguyen # your name (or website title) here
logo: "/images/IMG_7492.jpeg?raw=true" # your photo (or logo) here images/IMG_7492.jpeg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Duyen, a Master's student in Applied Data Science at University of Southern California. I have deep passion for data analytics/data science and always open to learn and grow my skillset.
  <br><br>
  Hope to connect with you soon!
  <br><br>
  <a href="https://www.linkedin.com/in/duyen21/">View My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-650SVG95FP # your Google Analytics tracking ID here
