title: Duyen (Doo-win) Nguyen # your name (or website title) here
logo: "/images/IMG_7492.jpeg?raw=true" # your photo (or logo) here images/IMG_7492.jpeg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Duyen, an incoming Master's student @ USC. I'm now in my last semester finishing up my Bachelor's degree in Industrial Engineering @ UCF. I found out my passion for data science while working at 
  <br><br>
  Hope to connect with you soon!
  <br><br>
  <a href="https://www.linkedin.com/in/duyen21/">View My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-650SVG95FP # your Google Analytics tracking ID here
