title: Duyen Nguyen # your name (or website title) here
logo: "/images/IMG_7492.jpeg?raw=true" # your photo (or logo) here images/IMG_7492.jpeg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, my name is Duyen Nguyen, an IE at UCF
  <br><br>
  Hello
  <br><br>
  <a href="https://www.linkedin.com/in/duyen21/">View My LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-650SVG95FP # your Google Analytics tracking ID here
