title: Duyen Nguyen # your name (or website title) here
logo: "/images/IMG_7492.jpeg?raw=true" # your photo (or logo) here images/IMG_7492.jpeg
description: # your text below (remove <br> elements if you don't need line breaks)
  '      ' <a href="https://drive.google.com/file/d/1eGH_SPiwwG1QROpEJ7shJFs3OB4ueLlG/view?usp=sharing"> Resume </a> |
  <a href="https://www.linkedin.com/in/duyen21/"> LinkedIn</a> | 
  <a href="https://github.com/duyen21"> Github</a>
  <br><br>
  Hi, I'm Duyen (pronounced as Doo-win) - a Master's student in Applied Data Science at University of Southern California. I have strong passion for data analytics/data science and always open to learn and grow my skillset.
  <br><br>


theme: jekyll-theme-minimal
google_analytics: G-650SVG95FP # your Google Analytics tracking ID here
